### ISSUE TITLE
The website menu is non-functional without JS

### ISSUE THREAD

**Issue by KOLANICH** [facebook/mariana-trench#42]
Likely should be rewritten in HTML5 + CSS.

**Comment by arthaud** [comment]
We accept pull requests if that's something you would want to do :)

**Comment by arthaud** [comment]
The website is auto-generated by docusaurus, an open source tool.
You can still access the documentation in markdown if you do not have Javascript enabled: https://github.com/facebook/mariana-trench/blob/main/documentation/website/documentation/getting_started.md
Will close this for now since there is a workaround.
