### ISSUE TITLE
[Shim + Lifecycle] Cannot propagate in different lifecycle functions of fragment

### ISSUE THREAD

**Issue by houugen** [facebook/mariana-trench#97]
Thanks for such a good tool，I have a problem with the new feature - shim

Modifications to the example code in the docs - flow taint in different lifecycle functions so it doesn't check out,  only works fine `getArguments` and `sink` within the same function，Guess it's a problem with the  `this` pointer

```
class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedinstanceState) {
        if (savedInstanceState == null) {
            Fragment myFragment = new MyFragment();
            myFragment.setArguments(getTaintedBundle());  // Source
            getSupportFragmentManager().beginTransaction()
                .setReorderingAllowed(true)
                .add(R.id.fragment_container_view, myFragment, null)  // FragmentManager handles `myFragment`'s lifecycle.
                .commit();
        }
    }
}

class MyFragment extends Fragment {
    private Bundle bundle;
    
    @Override
    public void onCreate(Bundle savedInstanceState) {
        this.bundle = getArguments(); // Issue if `mArguments` is tainted using `setArguments()`
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        sink(this.bundle);
    }
}
```

Configure and enable parameters correctly，used --lifecycles-paths & --shims-paths

**lifecycles**:

```
{
    "base_class_name": "Landroidx/fragment/app/Fragment;",
    "method_name": "xfragment_lifecycle_wrapper",
    "callees": [
      {
        "method_name": "onCreate",
        "return_type": "V",
        "argument_types": [
          "Landroid/os/Bundle;"
        ]
      },
      {
        "method_name": "onViewCreated",
        "return_type": "V",
        "argument_types": [
          "Landroid/view/View;",
          "Landroid/os/Bundle;"
        ]
      }
   ]
}
```

**shims-paths**:

```
{
    "find": "methods",
    "where": [
        {
            "constraint": "signature",
            "pattern": "Landroidx/fragment/app/FragmentTransaction;\\.add:\\(ILandroidx/fragment/app/Fragment;.*"
        }
    ],
    "shim": {
        "callees": [
            {
                "type_of": "Argument(2)",
                "lifecycle_name": "xfragment_lifecycle_wrapper"
            }
        ]
    }
}
```

**Comment by anwesht** [comment]
> Guess it's a problem with the this pointer

The problem here is that taint is not propagated from `setArguments()` to `getArguments()` without specifying the models for it. You will want to specify: 
```
{
  "find": "methods",
  "where": [
    {
      "constraint": "signature",
      "pattern": "Landroidx/fragment/app/Fragment;\\.setArguments:.*"
    }
  ],
  "model": {
    "propagation": [
      {
        "input": "Argument(1)",
        "output": "Argument(0).mArguments"
      }
    ]
 }
},
{
  "find": "methods",
  "where": [
    {
      "constraint": "signature",
      "pattern": "Landroidx/fragment/app/Fragment;\\.getArguments:.*"
    }
  ],
  "model": {
    "propagation": [
      {
        "input": "Argument(0).mArguments",
        "output": "Return"
      }
    ]
  }
}
```

**Comment by houugen** [comment]
@anwesht Thank you for your answer。but my above code can already propagate the taint from `setArguments` to `getArguments` through shim, it just can't be propagated to the `onViewCreated` method through the `onCreate` method of the Fragment class. So the propagation model you defined cannot solve this problem

**Comment by anwesht** [comment]
Oh apologies, I misread the issue :(.

So, if I understand correctly this time, the model for `xfragment_lifecycle_wrapper()` method in your example would simply have a sink on port `Argument(0).bundle`. But, as I mentioned in my previous comment, `setArguments()` will taint the port `Argument(0).mArgument`, hence no flow will be detected.

This is because mariana-trench only infers propogations from `arguments` to `return` port. To capture the flow you are describing, the model for `onCreate()` would need to have the propagation from `Argument(0).mArguments` to `Argument(0).bundle`, which will not be inferred. Adding this model manually however, should capture the flow. 

> only works fine getArguments and sink within the same function

So yes, sort of. You can still have interprocedural flows but the _root callable_ of the issue has to be one of the lifecycle methods and not the lifecycle wrapper method. eg.
```
void onCreate() {  // root callable
  Bundle bundle = getBundle();  // source trace of any length   
  processBundle(bundle);  // sink trace of any length
}

Bundle getBundle() {
  Bundle bundle = getArguments();
  // do stuff
  return bundle;
}

void processBundle(Bundle bundle) {
  sink(bundle);
}
```

Just to reiterate, the issue flow is only reported when the instance of `MyFragment` is tainted. In your example, reported at `MainActivity.onCreate()` where the instance of `MyFragment` is tainted with `getTaintedBundle()`. Without shims, you would likely have to over-approximate and define `getArguments()` as a source which would make triaging more difficult.

**Comment by houugen** [comment]
Thanks, this conclusion is consistent with what I got by experimenting and reading the source code

> So yes, sort of. You can still have interprocedural flows but the root callable of the issue has to be one of the lifecycle methods and not the lifecycle wrapper method

I am now using `getArguments` as the source and `UserInput` as the source to associate two issues😅

> Without shims, you would likely have to over-approximate and define getArguments() as a source which would make triaging more difficult.

Thanks again for your patient answer
